// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:cinebot/model/movie.dart';
import 'package:cinebot/model/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MovieAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MovieAdapter());
    registerAdapter(UserAdapter());
  }
}
